# Generated by Django 5.1.7 on 2025-03-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumApp', '0002_comment_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='industry_tag',
            field=models.CharField(choices=[('Technology & IT', 'Technology & IT'), ('Business & Finance', 'Business & Finance'), ('Engineering', 'Engineering'), ('Healthcare & Life Sciences', 'Healthcare & Life Sciences'), ('Education & Research', 'Education & Research'), ('Design', 'Design'), ('Legal & Compliance', 'Legal & Compliance'), ('Sciences', 'Sciences'), ('Government & Public Services', 'Government & Public Services')], default=('None', 'None'), max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='topic_tag',
            field=models.CharField(choices=[('Question', 'Question'), ('Job Listing', 'Job Listing'), ('Tip', 'Tip'), ('Shitpost', 'Shitpost'), ('Discussion', 'Discussion'), ('News', 'News'), ('Event', 'Event')], default=('None', 'None'), max_length=50),
        ),
    ]
