# Generated by Django 5.1.7 on 2025-03-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumApp', '0003_post_industry_tag_post_topic_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='industry_tag',
            field=models.CharField(choices=[('Technology-IT', 'Technology & IT'), ('Business-Finance', 'Business & Finance'), ('Engineering', 'Engineering'), ('Healthcare-Life Sciences', 'Healthcare & Life Sciences'), ('Education-Research', 'Education & Research'), ('Design', 'Design'), ('Legal-Compliance', 'Legal & Compliance'), ('Sciences', 'Sciences'), ('Government-Public Services', 'Government & Public Services')], default=('None', 'None'), max_length=50),
        ),
    ]
