# Generated by Django 5.1.6 on 2025-02-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
